try another thing

diff --git a/.github/workflows/publish-npm-package.yml b/.github/workflows/publish-npm-package.yml
--- a/.github/workflows/publish-npm-package.yml
+++ b/.github/workflows/publish-npm-package.yml
@@ -19,14 +19,11 @@ jobs:
     runs-on: ubuntu-latest
     permissions:
       contents: write
-    steps:
-      - name: Validate releaseType
-        run: |
-          case "${{ inputs.releaseType }}" in
-            patch|minor|major) ;;
-            *) echo "Error: Invalid releaseType. Allowed values are 'patch', 'minor', 'major'." && exit 1 ;;
-          esac
+    defaults:
+      run:
+        working-directory: ${{ inputs.packagePath }}
 
+    steps:
       - uses: actions/create-github-app-token@v1
         id: app-token
         with:
@@ -38,24 +35,28 @@ jobs:
           token: ${{ steps.app-token.outputs.token }}
           persist-credentials: false
 
+      - name: Validate releaseType
+        run: |
+          case "${{ inputs.releaseType }}" in
+            patch|minor|major) ;;
+            *) echo "Error: Invalid releaseType. Allowed values are 'patch', 'minor', 'major'." && exit 1 ;;
+          esac
+
       - uses: actions/setup-node@v4
         with:
           node-version: 20
 
       #  TODO: add build command
       # - name: Install dependencies and build
-      #   working-directory: ${{ inputs.packagePath }}
       #   run: |
       #     npm run co:login
       #     npm install
       #     npm run build
 
       # - name: Lint
-      #   working-directory: ${{ inputs.packagePath }}
       #   run: npm run lint --if-present
 
       # - name: Run Unit Tests
-      #   working-directory: ${{ inputs.packagePath }}
       #   run: npm run test:unit --if-present
 
       - name: Configure Git
@@ -64,7 +65,6 @@ jobs:
           git config --global user.email '166193391+MikeyPartonBot[bot]@users.noreply.github.com'
 
       - name: 'Automated Version Bump'
-        working-directory: ${{ inputs.packagePath }}
         run: |
           npm version ${{ inputs.releaseType }} --git-tag-version false
           NEW_VERSION=$(cat package.json | jq -r '.version')
